src/application/Projeto_Interdisciplinar/Controllers/AcessoController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto_Interdisciplinar.DAO;
using Projeto_Interdisciplinar.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Projeto_Interdisciplinar.Controllers
{
    public class AcessoController : PadraoController<UsuarioViewModel>
    {
        public AcessoController()
        {
            DAO = new UsuarioDAO();
            GeraProximoId = true;
        }

        protected override void ValidaDados(UsuarioViewModel model, string operacao)
        {
            base.ValidaDados(model, operacao);

            if (string.IsNullOrEmpty(model.LoginUsuario))
                ModelState.AddModelError("LoginUsuario", "Preencha o usuário.");

            if (string.IsNullOrEmpty(model.SenhaUsuario))
                ModelState.AddModelError("SenhaUsuario", "Preencha a senha.");

            if (model.IDCliente == 0)
                ModelState.AddModelError("IDCliente", "Escolha um cliente.");

            if (model.Perfil == "0")
                ModelState.AddModelError("Perfil", "Escolha um perfil.");

            // Imagem será obrigatório apenas na inclusão.
            // Na alteração iremos considerar a que já estava salva.

            if (model.Imagem == null && operacao == "I")
                ModelState.AddModelError("Imagem", "Escolha uma imagem.");

            if (model.Imagem != null && model.Imagem.Length / 1024 / 1024 >= 2)
                ModelState.AddModelError("Imagem", "Imagem limitada a 2 mb.");

            if (ModelState.IsValid)
            {
                //na alteração, se não foi informada a imagem, iremos manter a que já estava salva.
                if (operacao == "A" && model.Imagem == null)
                {
                    UsuarioViewModel user = DAO.Consulta(model.Id);
                    model.ImagemEmByte = user.ImagemEmByte;
                }
                else
                {
                    model.ImagemEmByte = ConvertImageToByte(model.Imagem);
                }
            }
        }

        /// <summary>
        /// Converte a imagem recebida no form em um vetor de bytes
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }
    }
}

src/application/Projeto_Interdisciplinar/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Projeto_Interdisciplinar.Models;
using Projeto_Interdisciplinar.DAO;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_Interdisciplinar.Controllers
{
    public class ClienteController : PadraoController<ClienteViewModel>
    {
        public ClienteController()
        {
            DAO = new ClienteDAO();
            GeraProximoId = true;
        }

        protected override void ValidaDados(ClienteViewModel model, string operacao)
        {
            base.ValidaDados(model, operacao);

            if (string.IsNullOrEmpty(model.NomeCliente))
                ModelState.AddModelError("NomeCliente", "Preencha o nome.");
        }
    }
}

src/application/Projeto_Interdisciplinar/Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Projeto_Interdisciplinar.Models;
using Projeto_Interdisciplinar.DAO;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_Interdisciplinar.Controllers
{
    public class FornecedorController : PadraoController<FornecedorViewModel>
    {
        public FornecedorController()
        {
            DAO = new FornecedorDAO();
            GeraProximoId = true;
        }

        protected override void ValidaDados(FornecedorViewModel model, string operacao)
        {
            base.ValidaDados(model, operacao);

            if (string.IsNullOrEmpty(model.NomeFornecedor))
                ModelState.AddModelError("NomeFornecedor", "Preencha o nome.");
        }
    }
}

src/application/Projeto_Interdisciplinar/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Projeto_Interdisciplinar.Models;
using Projeto_Interdisciplinar.DAO;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Projeto_Interdisciplinar.Controllers
{
    public class ProdutoController : Controller
    {
        protected PadraoDAO<ProdutoViewModel> DAO { get; set; }

        protected bool GeraProximoId { get; set; } = true;

        protected string NomeViewIndex { get; set; } = "Index";

        protected string NomeViewForm { get; set; } = "Form";

        protected bool ExigeAutenticacao { get; set; } = false;

        public ProdutoController()
        {
            DAO = new ProdutoDAO();
        }

        protected void ValidaDados(ProdutoViewModel model, string operacao)
        {
            ModelState.Clear();

            if (operacao == "I" && DAO.Consulta(model.Id) != null)
                ModelState.AddModelError("Id", "Código já está em uso!");

            if (operacao == "A" && DAO.Consulta(model.Id) == null)
                ModelState.AddModelError("Id", "Este registro não existe!");

            if (model.Id <= 0)
                ModelState.AddModelError("Id", "Id inválido!");

            if (string.IsNullOrEmpty(model.NomeProduto))
                ModelState.AddModelError("NomeFornecedor", "Preencha o nome.");

            if (model.PrecoProduto <= 0)
                ModelState.AddModelError("PrecoProduto", "Digite um valor válido.");

            // Imagem será obrigatório apenas na inclusão.
            // Na alteração iremos considerar a que já estava salva.

            if (model.Imagem == null && operacao == "I")
                ModelState.AddModelError("Imagem", "Escolha uma imagem.");

            if (model.Imagem != null && model.Imagem.Length / 1024 / 1024 >= 2)
                ModelState.AddModelError("Imagem", "Imagem limitada a 2 mb.");

            if (ModelState.IsValid)
            {
                //na alteração, se não foi informada a imagem, iremos manter a que já estava salva.
                if (operacao == "A" && model.Imagem == null)
                {
                    ProdutoViewModel produto = DAO.Consulta(model.Id);
                    model.ImagemEmByte = produto.ImagemEmByte;
                }
                else
                {
                    model.ImagemEmByte = ConvertImageToByte(model.Imagem);
                }
            }
        }

        /// <summary>
        /// Converte a imagem recebida no form em um vetor de bytes
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public byte[] ConvertImageToByte(IFormFile file)
        {
            if (file != null)
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    return ms.ToArray();
                }
            else
                return null;
        }

        public IActionResult Detalhes()
        {
            ExigeAutenticacao = false;

            ProdutoDAO dao = new ProdutoDAO();

            var lista = dao.Listagem();

            if (lista.Count == 0)
                return View("Index", "Home");
            else
                return View(lista);
        }

        public virtual IActionResult Index()
        {
            try
            {
                var lista = DAO.Listagem();

                return View(NomeViewIndex, lista);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public virtual IActionResult Create()
        {
            try
            {
                ViewBag.Operacao = "I";
                ProdutoViewModel model = Activator.CreateInstance(typeof(ProdutoViewModel)) as ProdutoViewModel;
                PreencheDadosParaView("I", model);

                PreparaCombos();

                return View(NomeViewForm, model);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        protected virtual void PreencheDadosParaView(string Operacao, ProdutoViewModel model)
        {
            if (GeraProximoId && Operacao == "I")
                model.Id = DAO.ProximoId();
        }

        public virtual IActionResult Save(ProdutoViewModel model, string Operacao)
        {
            try
            {
                ValidaDados(model, Operacao);

                if (ModelState.IsValid == false)
                {
                    ViewBag.Operacao = Operacao;
                    PreencheDadosParaView(Operacao, model);
                    PreparaCombos();

                    return View(NomeViewForm, model);
                }
                else
                {
                    if (Operacao == "I")
                        DAO.Insert(model);
                    else
                        DAO.Update(model);

                    return RedirectToAction(NomeViewIndex);
                }
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult Edit(int id)
        {
            try
            {
                ViewBag.Operacao = "A";
                var model = DAO.Consulta(id);
                PreparaCombos();

                if (model == null)
                    return RedirectToAction(NomeViewIndex);
                else
                {
                    PreencheDadosParaView("A", model);

                    return View(NomeViewForm, model);
                }
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                DAO.Delete(id);

                return RedirectToAction(NomeViewIndex);
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public IActionResult Visualizar(int id)
        {
            try
            {
                ViewBag.Operacao = "V";
                var model = DAO.Consulta(id);
                PreparaCombos();

                if (model == null)
                    return RedirectToAction(NomeViewIndex);
                else
                {
                    PreencheDadosParaView("A", model);

                    return View(NomeViewForm, model);
                }
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.ToString()));
            }
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            ViewBag.Logado = HelperController.VerificaUserLogado(HttpContext.Session);
            ViewBag.Perfil = HelperController.VerificaPerfil(HttpContext.Session);
        }

        #region Combo Box
        private void PreparaCombos()
        {
            ClienteDAO daoCliente = new ClienteDAO();
            FornecedorDAO daoFornecedor = new FornecedorDAO();

            var clientes = daoCliente.Listagem();
            var fornecedores = daoFornecedor.Listagem();

            List<SelectListItem> listaFornecedores = new List<SelectListItem>();

            listaFornecedores.Add(new SelectListItem("Selecione um fornecedor...", "0"));

            foreach (var fornecedor in fornecedores)
            {
                SelectListItem item = new SelectListItem(fornecedor.NomeFornecedor, fornecedor.Id.ToString());
                listaFornecedores.Add(item);
            }

            ViewBag.Fornecedores = listaFornecedores;
        }
        #endregion
    }
}

src/application/Projeto_Interdisciplinar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.cdnfonts.com/css/fresh-steak" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/Shared/layout.js"></script>

    @*essa parte abaixo é para permitir adicionar um css no head a partir de qualquer página*@
    @RenderSection("styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-family: 'Fresh Steak', sans-serif;">SmartMart</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Detalhes">Produtos</a>
                       </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carrinho" asp-action="Index">Carrinho de Compras</a>
                       </li>
                      @if (ViewBag.Logado == true)
                       {
                           @if (ViewBag.Perfil == "Funcionario")
                           {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Gráficos Demonstrativos</a>
                                </li>
                           }
                           
                           @if (ViewBag.Perfil == "Administrador")
                            {
                                 <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="Acesso" asp-action="Index">Controle de Acesso</a>
                                 </li>
                           
                                 <li class="nav-item dropdown">
                                     <a class="nav-link dropdown-toggle text-dark" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dados Gerais</a>
                                     <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                         <a class="dropdown-item text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                                         <a class="dropdown-item text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                                         <a class="dropdown-item text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                                     </div>
                                 </li>
                            }

                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Autenticacao" asp-action="LogOff">Logoff</a></li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link text-dark" href="javascript:modalLogin()">Login</a></li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-muted footer">
        <div class="container">
            &copy; 2023 - Powered by SmartMart - <a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


    <div class="modal" id="modal_validacao">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="titulo-modal"></h2>
                    <button type="button" class="close btn" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body">

                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</body>
</html>