src/application/Projeto_Interdisciplinar/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projeto_Interdisciplinar.Models;
using Projeto_Interdisciplinar.DAO;

namespace Projeto_Interdisciplinar.Controllers
{
    public class AutenticacaoController : Controller
    {
        public ActionResult _Login()
        {
            return PartialView();
        }

        public IActionResult FazLogin(string LoginUsuario, string SenhaUsuario)
        {
            UsuarioDAO dao = new UsuarioDAO();

            var lista = dao.Listagem();

            foreach (var item in lista)
            {
                if (item.LoginUsuario == LoginUsuario && item.SenhaUsuario == SenhaUsuario)
                {
                    HttpContext.Session.SetString("Logado", "true");
                    HttpContext.Session.SetString("Perfil", item.Perfil);
                    return RedirectToAction("Index", "Home");
                }
            }

            ViewBag.Erro = "Usuário ou senha inválidos!";
            return RedirectToAction("Index", "Home");
        }

        public IActionResult LogOff()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/application/Projeto_Interdisciplinar/Views/Autenticacao/_Login.cshtml
@model UsuarioViewModel

@using (Html.BeginForm("FazLogin", "Autenticacao", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.LoginUsuario, labelText: "Usuário")
        @Html.TextBoxFor(model => model.LoginUsuario, new { @class = "form-control" } )
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SenhaUsuario, labelText: "Senha")
        @Html.PasswordFor(model => model.SenhaUsuario, new { @class = "form-control" } )
    </div>

    <button type="submit" class="btn btn-primary">Entrar</button>
}

@if (!string.IsNullOrEmpty(ViewBag.MensagemErro))
{
    <div class="alert alert-danger">@ViewBag.MensagemErro</div>
}